version: '3.3' # FIXME: '3.7'

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  portainer-data:
    driver: local

services:

  ssm:
    build:
      context: ../
      dockerfile: dockerX/ssm/Dockerfile.local
      args:
         IMAGE: "python:3.6.8"
    restart: on-failure
    env_file:
      - ssm/develop.env
    ports:
      - 8000:8000
    volumes:
      - ../ssm:/usr/src/ssm/
      - ./ssm:/usr/src/scripts/
#      - /opt/pycharm-2018.1.3/debug-eggs/:/usr/src/pycharm/debug-eggs/
    depends_on:
      - postgres
      - redis
    networks:
      - network

  worker:
    image: "python:3.6.8"
    command: >
      sh -c "cd /usr/src/ssm/ &&
            pip install -r requirements.txt &&
            /usr/local/bin/celery -A ssm worker -l DEBUG -c 1 -Q celery-general -n celery-general"
    restart: on-failure
    env_file:
      - ssm/develop.env
    volumes:
      - ../ssm:/usr/src/ssm/
#      - /opt/pycharm-2018.1.3/debug-eggs/:/usr/src/pycharm/debug-eggs/
    depends_on:
      - postgres
      - redis
      - ssm
    networks:
      - network

  postgres:
    image: "postgres:11.1-alpine"
    env_file:
      - ssm/develop.env
    ports:
      - 8998:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network

  redis:
    image: "redis:5.0.3-alpine"
    volumes:
      - redis-data:/data
    networks:
      - network

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - "8897:9000"
    networks:
      - network

  flower:
    image: "python:3.6.8"
    command: >
      sh -c "cd /usr/src/ssm/ &&
            pip install -r requirements.txt &&
            /usr/local/bin/celery flower -A ssm --address=0.0.0.0 --port=5555
            --broker=redis://redis:6379/1 --basic_auth=user1:password1,user2:password2"
    restart: on-failure
    env_file:
      - ssm/develop.env
    ports:
      - 5555:5555
    volumes:
      - ../ssm:/usr/src/ssm/
#      - /opt/pycharm-2018.3.3/debug-eggs/:/usr/src/pycharm/debug-eggs/
    depends_on:
      - postgres
      - redis
      - ssm
    networks:
      - network
